""" This file contains all configuration parameter for the simulation"""

"""Carla Parameter"""
CARLA_SERVER_PORT: int = 2000
CARLA_SERVER_HOST: str = "localhost"
CARLA_SERVER_FPS: int = 20
TRAFFIC_MANAGER_PORT: int = 8000

SCENE_CAMERA_LOCATION_X: float = -10
SCENE_CAMERA_LOCATION_Y: float = 0.0
SCENE_CAMERA_LOCATION_Z: float = 10.0

SCENE_CAMERA_ROTATION_PITCH: float = -20.0
SCENE_CAMERA_ROTATION_YAW: float = 0.0
SCENE_CAMERA_ROTATION_ROLL: float = 0.0

LEADER_SPAWN_LOCATION_X: float = 40.0
LEADER_SPAWN_LOCATION_Y: float = -190.0
LEADER_SPAWN_LOCATION_Z: float = 1
LEADER_SPAWN_ROTATION_YAW: float = 0.0

LEADER_CONTROLLER_KP: float = 1.0
LEADER_CONTROLLER_KD: float = 0
LEADER_CONTROLLER_KI: float = 0.05

MANAGED_VEHICLE_SPAWN_LOCATION_X: float = 19.0
MANAGED_VEHICLE_SPAWN_LOCATION_Y: float = -190.0
MANAGED_VEHICLE_SPAWN_LOCATION_Z: float = 1.0
MANAGED_VEHICLE_SPAWN_ROTATION_YAW: float = 0.0

MANAGED_VEHICLE_CONTROLLER_KP: float = 1.0
MANAGED_VEHICLE_CONTROLLER_KD: float = 0.0
MANAGED_VEHICLE_CONTROLLER_KI: float = 0.05

PYGAME_WINDOW_WIDTH: float = 1920
PYGAME_WINDOW_HEIGHT: float = 1080
ANTI_ALIASING: bool = True
SHOW_FPS: bool = True

DEBUG_MODE: bool = False
MOVE_SPECTATOR: bool = True

"""Safety Parameter"""
MANAGED_VEHICLE_SPEED_RANGE: float = 1.0
MANAGED_VEHICLE_ACCELERATION_RANGE: float = 0.1
OTHER_ACCELERATION_RANGE: float = 0.1
OTHER_VELOCITY_RANGE: float = 1.0
CONNECTION_STRENGTH_RANGE: float = 10