""" This file contains all configuration parameter for the simulation"""
"""Simulation parameter"""
MANUAL_SCENARIO_MODE: bool = True

"""Carla Parameter"""
CARLA_SERVER_PORT: int = 2000
CARLA_SERVER_HOST: str = "localhost"
CARLA_SERVER_FPS: int = 20
TRAFFIC_MANAGER_PORT: int = 8000

"""Camera Parameter"""
SCENE_CAMERA_LOCATION_X: float = -10
SCENE_CAMERA_LOCATION_Y: float = 0.0
SCENE_CAMERA_LOCATION_Z: float = 10.0

SCENE_CAMERA_ROTATION_PITCH: float = -20.0
SCENE_CAMERA_ROTATION_YAW: float = 0.0
SCENE_CAMERA_ROTATION_ROLL: float = 0.0

LEADER_CAMERA_LOCATION_X: float = -10
LEADER_CAMERA_LOCATION_Y: float = 0
LEADER_CAMERA_LOCATION_Z: float = 5

LEADER_CAMERA_ROTATION_PITCH: float = -20
LEADER_CAMERA_ROTATION_YAW: float = 0
LEADER_CAMERA_ROTATION_ROLL: float = 0

"""Spawn Parameter"""
LEADER_SPAWN_LOCATION_X: float = 30.0
LEADER_SPAWN_LOCATION_Y: float = -190.0
LEADER_SPAWN_LOCATION_Z: float = 1
LEADER_SPAWN_ROTATION_YAW: float = 0.0

LEADER_CONTROLLER_KP: float = 1.0
LEADER_CONTROLLER_KD: float = 0
LEADER_CONTROLLER_KI: float = 0.05

MANAGED_VEHICLE_SPAWN_LOCATION_X: float = 19.0
MANAGED_VEHICLE_SPAWN_LOCATION_Y: float = -190.0
MANAGED_VEHICLE_SPAWN_LOCATION_Z: float = 2.0
MANAGED_VEHICLE_SPAWN_ROTATION_YAW: float = 0.0

MANAGED_VEHICLE_CONTROLLER_KP: float = 1.0
MANAGED_VEHICLE_CONTROLLER_KD: float = 0.0
MANAGED_VEHICLE_CONTROLLER_KI: float = 0.05

NUMBER_OF_MANAGED_VEHICLES: int = 2

PYGAME_WINDOW_WIDTH: int = 1920
PYGAME_WINDOW_HEIGHT: int = 1080

MANUAL_CONTROL_WINDOW_WIDTH: int = 1280
MANUAL_CONTROL_WINDOW_HEIGHT: int = 720
ANTI_ALIASING: bool = True
SHOW_FPS: bool = True

DEBUG_MODE: bool = False
MOVE_SPECTATOR: bool = True

"""Safety Parameter"""
SPEED_THRESHOLD_FACTOR: float = 0.5 # [s]
MAX_ACCELERATION: float = 8.0 # [m/s²]
MAX_DECELERATION: float = -14.0 #[m/s²]
DELAY_THRESHOLD: float = 5.0 #[ms]
DISTANCE_THRESHOLD_FACTOR: float = 1.0 #[m]